### ISSUE TITLE
Unable to access PADv2 through Baidu Pan

### ISSUE THREAD

**Issue by aycatakmaz** [lhc1224/OSAD_Net#1]
Hi,

First of all, thank you very much for this great work and also for making your code and data publicly available! For a research project, I would like to download PADv2, however since I am located in Switzerland I was unable to create a Baidu account to access the dataset through Baidu Pan. Would it be possible for you to upload PADv2 on Google Drive as well?

Thank you very much for your time!

Best,
Ayça

**Comment by lhc1224** [comment]
I have uploaded PADv2 dataset to https://drive.google.com/file/d/1TMWYMgO2GRM9ScEMCqEBwCPYk-UWBURD/view?usp=sharing

**Comment by aycatakmaz** [comment]
Thanks a lot!
