### ISSUE TITLE
What's the difference between PADv2 Part1 vs. PADv2 Part2?

### ISSUE THREAD

**Issue by cjiang2** [lhc1224/OSAD_Net#5]
Hello,

PADv2 Part1 can be found with both Google Drive and BaiduPan. However, for Part2, only BaiduPan is provided. To replicate paper results, are both part1 and part2 files needed? If so, how do one use the files in part2?

**Comment by lhc1224** [comment]
Part I and Part II are completely different images, and the results of the paper only use images from Part I. Part II provides unlabeled images.

**Comment by cjiang2** [comment]
> Part I and Part II are completely different images, and the results of the paper only use images from Part I. Part II provides unlabeled images.

Many thanks!
