### ISSUE TITLE
Folder structure of PADv2 dataset

### ISSUE THREAD

**Issue by cjiang2** [lhc1224/OSAD_Net#7]
Hello, I'm trying to understand how to use the PADv2 dataset for my own project, and I'm a bit confused about the overall folder structure: 

1. In the "test" folder of any division, there are two folders, "gt" and "masks", while in "train" folder, only "masks" is present. What's the difference between "gt" and "masks" in "test" folder?

2. Suppose that I am to replicate the Unet in the comparsion experiment. For one division, I use the "images" and "masks" in "train" to train the network and perform binary image segmentation ignoring the affordance. To replicate the paper testing results, I use the "images" and "masks" in "test"? Again what's the purpose of "gt" in "test" folder of each division?

3. All txt files with "ref" are for few-shot experiments, i.e. first item is the to-be-tested/query image, followed by 3 support images? What's the difference among txt files? (e.g. what's the difference between test_ref.txt vs. test_ref_2.txt)

4. This will be a tough question. I read from the paper that the dataset is constructed from MSCOCO and ImageNet. Is it possible to allocate which specific division of the two datasets the images come from? (e.g. is it from the Train2014 subset of MSCOCO? What's the original imgid?)

**Comment by lhc1224** [comment]
1.There should be no difference between gt and masks
2.
3. Different ref_test files correspond to different numbers of query
4. The original distribution of image sources is also difficult for me to answer at the moment

**Comment by cjiang2** [comment]
> 1.There should be no difference between gt and masks 2. 3. Different ref_test files correspond to different numbers of query 4. The original distribution of image sources is also difficult for me to answer at the moment

Thanks. I will close the issue for now.
